/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    BookmarkButton: typeof import('./src/components/BookmarkButton.vue')['default']
    CommentActions: typeof import('./src/components/comment/CommentActions.vue')['default']
    CommentContent: typeof import('./src/components/comment/CommentContent.vue')['default']
    CommentEditor: typeof import('./src/components/comment/CommentEditor.vue')['default']
    CommentItem: typeof import('./src/components/comment/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/comment/CommentList.vue')['default']
    CommentListItem: typeof import('./src/components/search/CommentListItem.vue')['default']
    CommentReplyEditor: typeof import('./src/components/comment/CommentReplyEditor.vue')['default']
    CommentSkeleton: typeof import('./src/components/comment/CommentSkeleton.vue')['default']
    CommentTree: typeof import('./src/components/comment/CommentTree.vue')['default']
    CommunityForm: typeof import('./src/components/community/CommunityForm.vue')['default']
    CommunityInfoCard: typeof import('./src/components/community/CommunityInfoCard.vue')['default']
    CommunitySelector: typeof import('./src/components/post/CommunitySelector.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileUploader: typeof import('./src/components/upload/FileUploader.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HotCommunitiesList: typeof import('./src/components/trending/HotCommunitiesList.vue')['default']
    HotPostsList: typeof import('./src/components/trending/HotPostsList.vue')['default']
    HotUsersList: typeof import('./src/components/trending/HotUsersList.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MarkdownEditor: typeof import('./src/components/post/MarkdownEditor.vue')['default']
    MemberActions: typeof import('./src/components/community/MemberActions.vue')['default']
    MemberListItem: typeof import('./src/components/community/MemberListItem.vue')['default']
    PasswordEditDialog: typeof import('./src/components/user/PasswordEditDialog.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostForm: typeof import('./src/components/post/PostForm.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    ProfileEditDialog: typeof import('./src/components/user/ProfileEditDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultsList: typeof import('./src/components/search/SearchResultsList.vue')['default']
    SearchSuggestions: typeof import('./src/components/search/SearchSuggestions.vue')['default']
    SearchTabs: typeof import('./src/components/search/SearchTabs.vue')['default']
    UserListItem: typeof import('./src/components/search/UserListItem.vue')['default']
    UserTabs: typeof import('./src/components/user/UserTabs.vue')['default']
    VoteButton: typeof import('./src/components/comment/VoteButton.vue')['default']
    VoteButtons: typeof import('./src/components/VoteButtons.vue')['default']
  }
}
